### PR TITLE
Ui changes

### PR DESCRIPTION
**Pull request by iamjigz**

### CODE REVIEW

**Comment by iamjigz** [comment]
[2.4 Add or setup UI for login, model selection (frontend only)](https://trello.com/c/E7HD9JVL/14-24-add-or-setup-ui-for-login-model-selection-frontend-only)

**Comment by iamjigz** [comment]
[Settings dialog adjustments](https://trello.com/c/JQUBkA7N/26-settings-dialog-adjustments)

**Comment by nvlled** [comment]
2019-03-02-211004_282x550_scrot
You should entirely remove the grid tab as well since it doesn't show up by default.

**Comment by iamjigz** [comment]
That's strange. It shows on mine but let me remove it.

Edit: Would it be alright if I just set the tab-item to selected? We'd have to remove the tab widget in the controller and I think we can just leave that in case we need to add additional settings.

**Comment by nvlled** [comment]
Okay, but for the mean time you can just hide the tab to fully conform with the client request:
```css
.settings-section-preferences .tab-list {
    display: none;
}
```

**Comment by iamjigz** [comment]
Done

**Review by nvlled — APPROVED** [review]

**Pull request merged**
