### PR TITLE
Implement color counter

### PR DESCRIPTION
**Pull request by nvlled**

### CODE REVIEW

**Review by iamjigz — CHANGES_REQUESTED** [review]
Can you fire the update function of ColorCounterController when an image is imported? It only updates when the canvas is modified (mousedown event i think). I'll merge it after that. Thanks!

**Comment by nvlled** [comment]
It looks like the problem is that importing images adds several layers to the canvas, whereas I only count on the first layer. It's either I count from all the layers or I just merge the layers when importing. I'll see which one is easier to implement.

**Comment by iamjigz** [comment]
That's what I thought too but apparently after the image is imported and you modify it, the color counter works. Would making a subtle change in the canvas (or on the layer) at runtime fire the same event?

**Comment by nvlled** [comment]
Okay, I looked at it but the actual problem is this: _only_ the colors in the palette are counted since that was the original intent.
We need to ask the client how to handle this. Possible solutions are:

- remove all the colors that are not in the palette (easier, but may result in broken images)
- convert the unknown colors to the closest color found in the palette (more difficult to implement)

**Comment by nvlled** [comment]
This is what it looks like when removing the colors that are not in the palette:
toad 1

**Comment by nvlled** [comment]
# Original image
toad

# Modified to palette colors
toad 3

If this is alright with the client, then we can go with this.

**Comment by nvlled** [comment]
Never mind about more difficult to implement, I've done option 2 and it's better.

**Comment by iamjigz** [comment]
Looks good to me. We'll have the client test this too.

**Comment by iamjigz** [comment]
[2.1 Add color counters on palette](https://trello.com/c/8sReQsWt/4-21-add-color-counters-on-palette)

**Review by iamjigz — APPROVED** [review]

**Pull request merged**
