### PR TITLE
Fix background transparency

### PR DESCRIPTION
**Pull request by nvlled**
- fix button for setting background transparency
- replace transparent pixels as white when exporting to PDF

### CODE REVIEW

**Review by iamjigz — APPROVED** [review]
LGTM

**Comment by nvlled** [comment]
[Background selection](https://trello.com/c/AYJ6eUxU/30-background-selection)

**Comment by nvlled** [comment]
[Transparency in PNG export](https://trello.com/c/pRwT8Ee3/29-transparency-in-png-export)

**Comment by nvlled** [comment]
[Transparency in PNG export](https://trello.com/c/pRwT8Ee3/29-transparency-in-png-export)

**Pull request merged**
