### PR TITLE
Export pdf and change dpi

### PR DESCRIPTION
**Pull request by nvlled**

### CODE REVIEW

**Comment by nvlled** [comment]
I did not thoroughly check if the pdf size is correct.

**Comment by iamjigz** [comment]
I might not be testing this correctly but the pdf exported only show the grid in black with a header.

**Comment by nvlled** [comment]
Confirmed, it only works in latest chrome. I'll check what's the problem.

**Comment by iamjigz** [comment]
[2.3 Export to pdf](https://trello.com/c/lA815yLe/24-23-export-to-pdf)

**Comment by iamjigz** [comment]
Grid looks wonderful. Great job!

**Review by iamjigz — APPROVED** [review]
LGTM

**Pull request merged**
